# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnsvard" do
  name "dnsvard"
  desc "Local development networking daemon for stable hostnames across worktrees"
  homepage "https://github.com/comment-slayer/dnsvard"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnsvard"

  on_macos do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_amd64.tar.gz"
      sha256 "b7262f43d184409a6505d301ea55cb39c0c157569fa70b0e87f41d000f9d5157"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_arm64.tar.gz"
      sha256 "0738bca29ae9d55acb14db508378156b29ff0aad9e867d641ff8773a3926ee78"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_amd64.tar.gz"
      sha256 "769180fac746537c5cca840890149692ef18ed7ec21e58c0d83cd506f74db1df"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_arm64.tar.gz"
      sha256 "e9aa653c1bb1620bc3346a5a7695fd90608eed499b672f518bf1684eabe0bfa5"
    end
  end

  # No zap stanza required
end
