# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnsvard" do
  name "dnsvard"
  desc "Local development networking daemon for stable hostnames across worktrees"
  homepage "https://github.com/comment-slayer/dnsvard"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnsvard"

  on_macos do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_amd64.tar.gz"
      sha256 "775879810d71ad5857f98d6f3cd72f42095f81860638b05d7e1520234d7e8419"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_arm64.tar.gz"
      sha256 "ddf8f1f8906390d9748291ec331dd7e6d0fef2080b5f67e2f3e155e1b31f83d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_amd64.tar.gz"
      sha256 "25dd6aee581f54a8e434d3a798c8cd962899f9b7645d0b97aafee7776eefd817"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_arm64.tar.gz"
      sha256 "0f5003d09847b7e9f8de3f4dc756f6f4003644999e94a80d04ed6695da040502"
    end
  end

  # No zap stanza required
end
