# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnsvard" do
  name "dnsvard"
  desc "Local development networking daemon for stable hostnames across worktrees"
  homepage "https://github.com/comment-slayer/dnsvard"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnsvard"

  on_macos do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_amd64.tar.gz"
      sha256 "05e59e87cbad6ebb47e2ff8450984a2b8395f69bd933e3f490606982b20c7fe9"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_darwin_arm64.tar.gz"
      sha256 "b4653b1f16f5fab777c51e18c524ea5b8bb651046b09d5b983169a0cfefa569d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_amd64.tar.gz"
      sha256 "a1788ae980fa38b923c227231d5b3a675210f01a75fd652b99430b7913b63308"
    end
    on_arm do
      url "https://github.com/comment-slayer/dnsvard/releases/download/v#{version}/dnsvard_v#{version}_linux_arm64.tar.gz"
      sha256 "1ae54a8df90151ce3d1edfd74127fb8cae7d30d6b676bd89e57142febc157f42"
    end
  end

  # No zap stanza required
end
